routes/main_routes.py
import datetime
from flask import Blueprint, abort, app, flash, jsonify, render_template, redirect, request, current_app, session, url_for  # Removida a importação desnecessária de 'app' e 'url_for'
import jwt
from db import mysql  # Importe a instância do MySQL
import MySQLdb
from werkzeug.security import check_password_hash, generate_password_hash


main_routes = Blueprint('main_routes', __name__)

def minha_funcao(mysql):
    # Código que utiliza mysql.connection.cursor()
    pass

@main_routes.route('/')
def index():
    return render_template('index.html')

@main_routes.route('/login', methods=['POST', 'GET'])
def admin_login():
    if request.method == 'POST':
        username = request.form.get('username')
        password = request.form.get('password')

        cur = mysql.connection.cursor()
        cur.execute("SELECT * FROM admin WHERE usuario = %s AND senha = %s", (username, password))
        user = cur.fetchone()
        cur.close()

        if user:
            # Ajuste a rota de redirecionamento para 'main_routes.painel_admin'
            return redirect(url_for('main_routes.painel_admin'))
        else:
            return redirect(url_for('main_routes.unauthorized'))

    return render_template('login_admin.html')

@main_routes.route('/dados_clientes')
def dados_clientes():
    try:
        conexao = mysql.connection
        clientes = obter_dados_da_tabela_clientes(conexao)

        # Converter a lista de clientes em uma lista de dicionários
        dados = []
        for cliente in clientes:
            dados.append({
                'cpf': cliente[0],
                'nome_completo': cliente[1],
                'empresa': cliente[2],
                'funcoes': cliente[3]
            })

        # Retornar os dados em formato JSON
        return jsonify({'data': dados})
    except Exception as e:
        print(f"Erro: {str(e)}")
        return jsonify({'error': str(e)}), 500


# Função para obter dados da tabela clientes
def obter_dados_da_tabela_clientes(conexao):
    try:
        # Cria um cursor a partir da conexão
        cursor = conexao.cursor()

        # Consulta SQL para obter dados da tabela clientes
        consulta = "SELECT cpf, nome_completo, empresa, funcoes FROM clientes"
        cursor.execute(consulta)

        # Obtém todos os resultados
        clientes = cursor.fetchall()

        # Fecha o cursor
        cursor.close()

        return clientes  # Retorna diretamente a lista de clientes

    except Exception as e:
        print(f"Erro ao obter dados da tabela clientes: {str(e)}")
        # Trate o erro conforme necessário
        raise



@main_routes.route('/painel_admin')
def painel_admin():
    try:
        # Obtém a conexão do MySQL a partir do aplicativo Flask
        conexao = mysql.connection

        # Chama a função para obter dados da tabela clientes
        clientes = obter_dados_da_tabela_clientes(conexao)

        print(f"Clientes recebidos: {clientes}")  # Adicione esta linha para depuração

        # Renderiza a página HTML com os dados obtidos
        return render_template('painel_admin.html', clientes=clientes)

    except Exception as e:
        print(f"Erro ao obter dados da tabela clientes: {str(e)}")
        # Trate o erro conforme necessário, por exemplo, exibindo uma página de erro
        return render_template('erro.html', mensagem="Erro ao obter dados da tabela clientes")




@main_routes.route('/primeiro_acesso', methods=['GET', 'POST'])
def primeiro_acesso():
    if request.method == 'POST':
        # Obtém o nome de usuário do formulário
        username = request.form.get('username')

        # Consulta ao banco de dados para verificar se o usuário já existe
        cur = mysql.connection.cursor()
        cur.execute("SELECT usuario_cliente, senha_cliente FROM login_cliente WHERE usuario_cliente = %s", (username,))
        usuario = cur.fetchone()
        cur.close()

        if usuario:
            # Verifica se o usuário já tem senha cadastrada
            if usuario['senha_cliente']:
                flash('Usuário já cadastrado', 'error')
            else:
                # Armazena o nome de usuário na sessão
                session['current_user'] = username

                # Usuário existe, mas ainda não tem senha cadastrada, redireciona para a página de cadastro de senha
                flash('Redirecionando para o cadastro de senha', 'success')
                # Redirecionamento para a rota cadastro_senha
                return redirect(url_for('main_routes.cadastro_senha'))

        else:
            # Usuário não encontrado, pode lidar com isso conforme necessário
            flash('Usuário não encontrado', 'error')

    return render_template('primeiro_acesso.html')



@main_routes.route('/cadastro_senha', methods=['GET', 'POST'])
def cadastro_senha():
    if request.method == 'POST':
        # Obtém a senha do formulário
        senha = request.form.get('password')

        # Obtém o nome de usuário armazenado na sessão
        username = session.get('current_user')

        try:
            # Conecta ao banco de dados
            cur = mysql.connection.cursor()

            # Atualiza o banco de dados com a senha associada ao usuário
            cur.execute("UPDATE login_cliente SET senha_cliente = %s WHERE usuario_cliente = %s", (senha, username))

            # Commit da transação
            mysql.connection.commit()

            # Limpa a sessão após cadastrar a senha
            session.pop('current_user', None)

            flash('Senha cadastrada com sucesso', 'success')
            return redirect(url_for('main_routes.colaboradores'))

        except Exception as e:
            # Lidar com erros durante a inserção no banco de dados
            flash(f'Erro ao cadastrar a senha: {str(e)}', 'error')

        finally:
            # Certifique-se de fechar o cursor
            cur.close()

    return render_template('cadastro_senha.html')


# Função para verificar se o usuário está autenticado
def is_authenticated():
    return 'username' in session



# Rota para a página de login do colaborador no blueprint 'main_routes'
@main_routes.route('/login_colaborador')
def tela_login_colaborador():
    return render_template('login_colaborador.html')

# Rota para processar o formulário de login do colaborador no blueprint 'main_routes'
@main_routes.route('/autenticacao_cliente', methods=['POST'])
def submit_login_colaborador():
    error = None

    if request.method == 'POST':
        username = request.form['username']
        password = request.form['password']

        cur = mysql.connection.cursor()

        cur.execute("SELECT * FROM login_cliente WHERE usuario_cliente = %s", (username,))
        user = cur.fetchone()

        if user:
            if password == user['senha_cliente']:
                cur.execute("SELECT home, calendario, matricula, cadastro, secretaria, financeiro, professor FROM permissao WHERE cpf_cliente = %s", (user['cpf_cliente'],))
                permissions = cur.fetchone()

                if permissions:
                    token_payload = {
                        'username': user['usuario_cliente'],
                        'cpf': user['cpf_cliente'],
                        'home': permissions['home'],
                        'calendario': permissions['calendario'],
                        'matricula': permissions['matricula'],
                        'cadastro': permissions['cadastro'],
                        'secretaria': permissions['secretaria'],
                        'financeiro': permissions['financeiro'],
                        'professor': permissions['professor'],
                        'exp': datetime.datetime.utcnow() + datetime.timedelta(hours=1)
                    }

                    token = jwt.encode(token_payload, current_app.config['SECRET_KEY'], algorithm='HS256')
                    # Redireciona para a rota de índice do colaborador no blueprint 'main_routes' com o token como parâmetro
                    return redirect(url_for('main_routes.index_colaborador_blueprint', token=token))
                else:
                    error = 'Permissões não encontradas para o usuário'
            else:
                error = 'Senha incorreta'
        else:
            error = 'Usuário não encontrado'

        cur.close()

    # Redireciona para a rota de índice do colaborador no blueprint 'main_routes' com o erro como parâmetro
    return redirect(url_for('main_routes.index_colaborador_blueprint', error=error))



def is_token_valid(token):
    try:
        jwt.decode(token, current_app.config['SECRET_KEY'], algorithms=['HS256'])
        return True
    except jwt.ExpiredSignatureError:
        return False
    except jwt.InvalidTokenError:
        return False

    
@main_routes.route('/index_colaborador', endpoint='index_colaborador_blueprint')
def index_colaborador():
    token = request.args.get('token')

    if token and is_token_valid(token):
        # Adquira as permissões do token
        token_payload = jwt.decode(token, current_app.config['SECRET_KEY'], algorithms=['HS256'])
        permissions = {
            'home': token_payload.get('home', False),
            'calendario': token_payload.get('calendario', False),
            'matricula': token_payload.get('matricula', False),
            'cadastro': token_payload.get('cadastro', False),
            'secretaria': token_payload.get('secretaria', False),
            'financeiro': token_payload.get('financeiro', False),
            'professor': token_payload.get('professor', False),
        }

        return render_template('index_colaborador.html', permissions=permissions)
    else:
        # Redireciona para a rota no blueprint
        return redirect(url_for('main_routes.tela_login_colaborador'))

    
@main_routes.route('/unauthorized')
def unauthorized():
    return render_template ('unauthorized.html')

@main_routes.route('/cadastrar_empresa', methods=['GET', 'POST'])
def cadastrar_empresa():

templates/cadastrar_empresa.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Cadastrar Empresa</title>
    <link href="https://cdn.jsdelivr.net/npm/tailwindcss@2.2.19/dist/tailwind.min.css" rel="stylesheet">
    <link rel="stylesheet" href="../static/styles/components/sidebar.css">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.8.0/font/bootstrap-icons.css" />
</head>

<body class="font-sans">

    <!-- Inicio do sidebar -->
    <span id="openSidebarButton" class="absolute text-white text-4xl top-5 left-4 cursor-pointer"
        >
        <i class="bi bi-list px-2 bg-gray-900 rounded-md"></i>
    </span>

    <div 
    id="sidebar"
    onclick="event.stopPropagation();"
    class="sidebar fixed top-0 bottom-0 lg:left-0 p-2 w-[300px] overflow-y-auto text-center bg-gray-900">

        <div class="text-gray-100 text-xl">
            <div class="p-2.5 mt-1 flex items-center">
                <i class="bi bi-app-indicator px-2 py-1 rounded-md bg-blue-600"></i>
                <h1 class="font-bold text-gray-200 text-[15px] ml-3">Sistema</h1>

                <div class="my-2 bg-gray-600 h-[1px]"></div>
            </div>
            <button class="close-button ml-28 " onclick="toggleSidebar()">
                &times;
            </button>

        </div>
        <div class="p-2.5 flex items-center rounded-md px-4 duration-300 cursor-pointer bg-gray-700 text-white">
            <i class="bi bi-search text-sm"></i>
            <input id="searchInput" type="text" placeholder="Search"
                class="text-[15px] ml-4 w-full bg-transparent focus:outline-none" />
        </div>
        <div id="optionsContainer">
            <a href="{{ url_for('main_routes.painel_admin') }}">
                <div
                    class="p-2.5 mt-3 flex items-center rounded-md px-4 duration-300 cursor-pointer hover:bg-blue-600 text-white">
                    <i class="bi bi-house-door-fill"></i>

                    <span class="text-[15px] ml-4 text-gray-200 font-bold">Home</span>

                </div>
            </a>
            <div class="my-4 bg-gray-600 h-[1px]"></div>
            <div class="p-2.5 mt-3 flex items-center rounded-md px-4 duration-300 cursor-pointer hover:bg-blue-600 text-white"
                onclick="dropdown_usuarios()">
                <i class="bi bi-people"></i>
                <div class="flex justify-between w-full items-center">
                    <span class="text-[15px] ml-4 text-gray-200 font-bold">Usuários</span>
                    <span class="text-sm rotate-180" id="arrow_usuarios">
                        <i class="bi bi-chevron-down"></i>
                    </span>
                </div>
            </div>
            
            <div class="text-left text-sm mt-2 w-4/5 mx-auto text-gray-200 font-bold" id="submenu_usuarios">
                <a href="{{ url_for('main_routes.adicionar_usuario') }}">
                <h1 class="cursor-pointer p-2 hover:bg-blue-600 rounded-md mt-1">
                    Cadastrar Usuário
                </h1>
                </a>
                <a href="{{ url_for('main_routes.painel_admin') }}">
                <h1 class="cursor-pointer p-2 hover:bg-blue-600 rounded-md mt-1">
                    Usuários Cadastrados
                </h1>
                </a>
            </div>
            <div class="my-4 bg-gray-600 h-[1px]"></div>
            <div class="p-2.5 mt-3 flex items-center rounded-md px-4 duration-300 cursor-pointer hover:bg-blue-600 text-white"
                onclick="dropdown_empresas()">
                <i class="bi bi-building"></i>
                <div class="flex justify-between w-full items-center">
                    <span class="text-[15px] ml-4 text-gray-200 font-bold">Empresas</span>
                    <span class="text-sm rotate-180" id="arrow_empresas">
                        <i class="bi bi-chevron-down"></i>
                    </span>
                </div>
            </div>
            <div class="text-left text-sm mt-2 w-4/5 mx-auto text-gray-200 font-bold" id="submenu_empresas">
                <a href="{{ url_for('main_routes.cadastrar_empresa') }}">
                <h1 class="cursor-pointer p-2 hover:bg-blue-600 rounded-md mt-1">
                    Cadastrar Empresa
                </h1>
                </a>
                <a href="{{ url_for('main_routes.visualizar_empresas') }}">
                <h1 class="cursor-pointer p-2 hover:bg-blue-600 rounded-md mt-1">
                    Empresas Cadastradas
                </h1>
                </a>
            </div>

            <div
                class="p-2.5 mt-3 flex items-center rounded-md px-4 duration-300 cursor-pointer hover:bg-blue-600 text-white">
                <i class="bi bi-box-arrow-in-right"></i>
                <span class="text-[15px] ml-4 text-gray-200 font-bold">Logout</span>
            </div>
        </div>
    </div>


<!-- Fim do sidebar -->    
   

    <div class="w-full max-w-md mx-auto mt-8">
    <h1 class="text-2xl font-bold mb-4">Cadastrar Nova Empresa</h1>

    {% with messages = get_flashed_messages() %}
    {% if messages %}
    <div class="mb-4">
        {% for message in messages %}
        <div class="bg-green-200 text-green-800 px-4 py-2 rounded">{{ message }}</div>
        {% endfor %}
    </div>
    {% endif %}
    {% endwith %}

    <form method="POST" action="{{ url_for('main_routes.cadastrar_empresa') }} " class="mb-4">
        <div class="mb-4">
            <label for="cnpj" class="block text-gray-600 text-sm font-semibold mb-2">CNPJ: *</label>
            <input type="text" name="cnpj" id="cnpj"
                class="shadow-sm bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500 dark:shadow-sm-light"
                maxlength="18" required>
        </div>

        <div class="mb-4">
            <label for="nome" class="block text-gray-600 text-sm font-semibold mb-2">Nome: *</label>
            <input type="text" name="nome" id="nome"
                class="shadow-sm bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500 dark:shadow-sm-light"
                required>
        </div>

        <div class="mb-4">
            <label for="contato" class="block text-gray-600 text-sm font-semibold mb-2">Contato: *</label>
            <input type="text" name="contato" id="contato"
                class="shadow-sm bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500 dark:shadow-sm-light "
                oninput="formatarContato(this)" maxlength="15" required>
        </div>

        <div class="mb-4">
            <label for="cep" class="block text-gray-600 text-sm font-semibold mb-2">CEP: *</label>
            <input type="text" name="cep" id="cep"
                class="shadow-sm bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500 dark:shadow-sm-light"
                maxlength="9" required>
        </div>

        <div class="mb-4">
            <label for="rua" class="block text-gray-600 text-sm font-semibold mb-2">Rua: *</label>
            <input readonly type="text" name="rua" id="rua"
                class="shadow-sm bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500 dark:shadow-sm-light"
                required>
        </div>

        <div class="mb-4">
            <label  for="bairro" class="block text-gray-600 text-sm font-semibold mb-2">Bairro: *</label>
            <input readonly type="text" name="bairro" id="bairro"
                class="shadow-sm bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500 dark:shadow-sm-light"
                required>
        </div>

        <div class="mb-4">
            <label for="numero" class="block text-gray-600 text-sm font-semibold mb-2">Número: *</label>
            <input type="text" name="numero" id="numero"
                class="shadow-sm bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500 dark:shadow-sm-light"
                maxlength="6" required>
        </div>

        <div class="mb-4">
            <label for="complemento" class="block text-gray-600 text-sm font-semibold mb-2">Complemento:</label>
            <input type="text" name="complemento" id="complemento"
                class="shadow-sm bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500 dark:shadow-sm-light">
        </div>

        <div class="mt-8">
            <button type="submit" class="bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded">
                Cadastrar Empresa
            </button>
        </div>
    </form>
</div>
    <script src="https://cdn.jsdelivr.net/npm/alpinejs@2.8.2/dist/alpine.min.js" defer></script>
    <script src="{{ url_for('static', filename='js/cadastrar_empresa.js') }}"></script>
    <script src="../static/js/components/sidebar.js"></script>
    <script src="../static/js/components/filtro_cep.js"></script>

</body>

</html>

templates/erro.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Serviço Fora do Ar</title>
    <link href="https://cdn.jsdelivr.net/npm/tailwindcss@2.2.19/dist/tailwind.min.css" rel="stylesheet">
</head>

<body class="font-sans flex items-center justify-center h-screen bg-gray-100">

    <div class="text-center">
        <h1 class="text-4xl font-bold text-red-500 mb-4">Serviço Fora do Ar</h1>
        <p class="text-gray-600 mb-4">Desculpe-nos pelo transtorno. O serviço está temporariamente indisponível.</p>
        <a href="{{ url_for('main_routes.admin_login') }}" class="bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded">Voltar</a>
    </div>

</body>

</html>

templates/index.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Minha Página Inicial</title>
    <link rel="stylesheet" href="{{ url_for('static', filename='styles/tailwind.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='styles/index.css') }}">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/tailwindcss@3.3.3/dist/tailwind.min.css">
</head>

<body class="bg-gray-200 p-8">
    <h1 class="text-3xl font-bold mb-4 text-center">Bem-vindo à minha página inicial!</h1>

    <div class="flex items-center justify-center">
        <!-- Botão Administrador -->
        <form action="{{ url_for('main_routes.admin_login') }}" method="get">
            <button type="submit" class="bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded">
                Administrador
            </button>
        </form>
    
        <!-- Botão Colaboradores -->
        <form action="{{ url_for('main_routes.tela_login_colaborador') }}" method="get">
            <button type="submit" class="bg-green-500 hover:bg-green-700 text-white font-bold py-2 px-4 rounded ml-2">
                Colaboradores
            </button>
        </form>
    </div>
    
</body>

</html>

templates/login_colaborador.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Login Colaborador</title>
    <link rel="stylesheet" href="{{ url_for('static', filename='styles/tailwind.css') }}">

    <script src="https://cdn.jsdelivr.net/gh/alpinejs/alpine@v2.x.x/dist/alpine.js" defer></script>
</head>

<body class="bg-gray-200 flex items-center justify-center min-h-screen">

    <div x-data="{ showErrorToast: {{ 'true' if error else 'false' }} }">
        <!-- Toast para mostrar mensagens de erro -->
        <div x-show.transition.duration.1000ms="showErrorToast"
             class="fixed top-0 right-0 mt-4 mr-4 bg-red-500 text-white p-4 rounded">
            {{ error }}
        </div>
    </div>

    <div class="md:h-screen w-full md:flex">
        <div class="md:w-1/2 bg-gradient-to-tr from-blue-800 to-purple-700 i justify-center items-center">
        </div>
        <div class="w-full md:w-1/2 flex justify-center items-center bg-white">
            <div class="container max-w-full mx-auto py-24 px-6">
                <div class="font-sans">
                    <div class="max-w-sm mx-auto px-6">
                        <div class="relative flex flex-wrap">
                            <div class="w-full relative">
                                <div class="mt-6">
                                    <div class="text-center font-semibold text-black">
                                        Login Colaborador
                                    </div>

                                    <!-- Defina o método e a ação do formulário -->
                                    <form class="mt-8" method="POST" action="{{ url_for('main_routes.submit_login_colaborador') }}">
                                        <div class="mx-auto max-w-lg">
                                            <div class="py-2">
                                                <span class="px-1 text-sm text-gray-600">Usuário</span>
                                                <input name="username" placeholder="" type="text"
                                                    class="text-md block px-3 py-2 rounded-lg w-full 
                                                    bg-white border-2 border-gray-300 placeholder-gray-600 shadow-md focus:placeholder-gray-500 focus:bg-white focus:border-gray-600 focus:outline-none">
                                            </div>
                                            <div class="py-2" x-data="{ show: true }">
                                                <span class="px-1 text-sm text-gray-600">Senha</span>
                                                <div class="relative">
                                                    <input name="password" placeholder=""
                                                        :type="show ? 'password' : 'text'" class="text-md block px-3 py-2 rounded-lg w-full 
                                                    bg-white border-2 border-gray-300 placeholder-gray-600 shadow-md
                                                    focus:placeholder-gray-500
                                                    focus:bg-white 
                                                    focus:border-gray-600  
                                                    focus:outline-none">
                                                    <div
                                                        class="absolute inset-y-0 right-0 pr-3 flex items-center text-sm leading-5">
                                                        <svg class="h-6 text-gray-700" fill="none" @click="show = !show"
                                                            :class="{'hidden': !show, 'block':show }"
                                                            xmlns="http://www.w3.org/2000/svg" viewbox="0 0 576 512">
                                                            <path fill="currentColor"
                                                                d="M572.52 241.4C518.29 135.59 410.93 64 288 64S57.68 135.64 3.48 241.41a32.35 32.35 0 0 0 0 29.19C57.71 376.41 165.07 448 288 448s230.32-71.64 284.52-177.41a32.35 32.35 0 0 0 0-29.19zM288 400a144 144 0 1 1 144-144 143.93 143.93 0 0 1-144 144zm0-240a95.31 95.31 0 0 0-25.31 3.79 47.85 47.85 0 0 1-66.9 66.9A95.78 95.78 0 1 0 288 160z">
                                                            </path>
                                                        </svg>
                                                        <svg class="h-6 text-gray-700" fill="none" @click="show = !show"
                                                            :class="{'block': !show, 'hidden':show }"
                                                            xmlns="http://www.w3.org/2000/svg" viewbox="0 0 640 512">
                                                            <path fill="currentColor"
                                                                d="M320 400c-75.85 0-137.25-58.71-142.9-133.11L72.2 185.82c-13.79 17.3-26.48 35.59-36.72 55.59a32.35 32.35 0 0 0 0 29.19C89.71 376.41 197.07 448 320 448c26.91 0 52.87-4 77.89-10.46L346 397.39a144.13 144.13 0 0 1-26 2.61zm313.82 58.1l-110.55-85.44a331.25 331.25 0 0 0 81.25-102.07 32.35 32.35 0 0 0 0-29.19C550.29 135.59 442.93 64 320 64a308.15 308.15 0 0 0-147.32 37.7L45.46 3.37A16 16 0 0 0 23 6.18L3.37 31.45A16 16 0 0 0 6.18 53.9l588.36 454.73a16 16 0 0 0 22.46-2.81l19.64-25.27a16 16 0 0 0-2.82-22.45zm-183.72-142l-39.3-30.38A94.75 94.75 0 0 0 416 256a94.76 94.76 0 0 0-121.31-92.21A47.65 47.65 0 0 1 304 192a46.64 46.64 0 0 1-1.54 10l-73.61-56.89A142.31 142.31 0 0 1 320 112a143.92 143.92 0 0 1 144 144c0 21.63-5.29 41.79-13.9 60.11z">
                                                            </path>
                                                        </svg>
                                                    </div>
                                                </div>
                                            </div>
                                            <p>Primeiro acesso? <a href="{{ url_for('main_routes.primeiro_acesso') }}"
                                                    class="font-medium text-blue-600 dark:text-blue-500 hover:underline">Clique
                                                    aqui</a></p>
                                            <button type="submit" class="mt-3 text-lg font-semibold 
                                                bg-gray-800 w-full text-white rounded-lg
                                                px-6 py-3 block shadow-xl hover:text-white hover:bg-black">
                                                Login
                                            </button>
                                        </div>
                                    </form>

                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</body>

</html>

templates/unauthorized.html
<!-- templates/unauthorized.html -->

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Unauthorized</title>
    <link rel="stylesheet" href="{{ url_for('static', filename='styles/tailwind.css') }}">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/tailwindcss@3.3.3/dist/tailwind.min.css">
</head>

<body class="bg-gray-200 flex items-center justify-center h-screen">
    <div class="text-center">
        <h1 class="text-4xl font-bold text-red-500 mb-4">Unauthorized</h1>
        <p class="text-gray-600 mb-8">Acesso não autorizado. Faça o login para acessar o sistema.</p>
        <a href="{{ url_for('main_routes.admin_login') }}" class="bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded">
            Login
        </a>        
    </div>
</body>

</html>